[package]
name = "iridium_graphics"
version = "0.1.0"
authors = ["Mikhail <12schneide@gmail.com>"]

[dependencies]
vulkano = "*"
vulkano-win = "*"
winit = "*"

iridium_core = { path = "../iridium_core", version = "*" }